import SiteHeader from "../../components/SiteHeader";
import SiteFooter from "../../components/SiteFooter";

const SECTIONS = [
 {title:"What is SintaChat?", paragraphs:["SintaChat is an anonymous chat platform for students aged 18 and above in the Philippines.","The platform allows students to connect and communicate without requiring the kind of public social identity commonly associated with traditional social media platforms.","There are no follower counts defining someone's popularity. There is no need to create an elaborate public persona before having a conversation. There is no requirement for two people to already know each other."]},
 {title:"Why \“Sinta\”?", paragraphs:["The name SintaChat comes from the Filipino word \“sinta,\” which is commonly associated with affection, fondness, and something or someone held dear.","The name also reflects where the platform began. SintaChat is being created by student developers from the Polytechnic University of the Philippines, where the word Sinta has a recognizable connection with the university and its community.","At PUP, SINTA is associated with the identity of the Polytechnic University of the Philippines and its academic community.","However, SintaChat itself is not limited to PUP students. It is not exclusively for one university, campus, course, organization, or student community. SintaChat is intended for eligible users 18 years old and above throughout the Philippines.","The name represents the roots of the project and the student developers behind it, while the platform itself is created for a wider Filipino community. SintaChat began with PUP student developers, but the conversations it enables can reach people across the country."]},
 {title:"Developed by PUP Students", paragraphs:["SintaChat is developed, maintained, and continuously improved by students from the Computer Engineering program of the Polytechnic University of the Philippines, particularly students specializing in Software Engineering and Network Engineering.","SintaChat gives its student developers an opportunity to transform the concepts they study into an actual digital platform that people can use.","Developing SintaChat involves far more than simply writing code. It includes planning system architecture, designing interfaces, managing databases, connecting frontend and backend services, handling real-time communication, configuring infrastructure, identifying bugs, improving performance, strengthening security, maintaining deployments, and continuously refining the overall platform.","For the team behind it, SintaChat represents the practical application of Computer Engineering, Software Engineering, and Network Engineering in a real and continuously evolving project."]},
 {title:"Created at PUP, built for students across the country", paragraphs:["SintaChat has its roots at the Polytechnic University of the Philippines because that is where its student developers come from. However, the platform is not exclusive to the PUP community.","SintaChat welcomes eligible students 18 years old and above from different parts of the Philippines, regardless of their university, profession, province, city, or background, subject to the platform's rules and policies.","The developers' connection to PUP represents the origin of the project. It does not define the limits of the SintaChat community. Someone does not need to be a PUP student to use SintaChat. Someone does not even need to be a student.","The platform is intended for Filipino students who meet its eligibility requirements and want an opportunity to talk with someone new."]},
 {title:"For students 18 years old and above", paragraphs:["SintaChat is intended for students aged 18 years old and above. Users accessing the platform are expected to meet the minimum age requirement and follow SintaChat's applicable Terms, Community Guidelines, and safety policies.","The 18+ requirement is an important part of how SintaChat defines its community. While anonymous communication can provide students with greater freedom and spontaneity, that freedom comes with responsibility.","Everyone using the platform should remember that there is another real person behind the screen. Being anonymous does not remove the expectation of respectful behavior. SintaChat is intended to provide a space where students can communicate while respecting boundaries, consent, privacy, and one another."]},
 {title:"Anonymous, but still human", paragraphs:["Anonymity should never be treated as permission to harm another person. SintaChat expects users to communicate responsibly.","Harassment, threats, exploitation, discriminatory abuse, impersonation, intimidation, illegal activities, and other harmful behavior should never become part of a healthy anonymous community."]},
 {title:"Protect your privacy", paragraphs:["Although SintaChat is designed around anonymous communication, users should always use good judgment when talking with strangers online.","Users should be careful about sharing sensitive personal information. Passwords, banking details, account credentials, government identification documents, exact home addresses, private financial information, and other highly sensitive details should never be casually shared with people met online.","Users should also think carefully before sharing personal contact information or other details that could reveal their identity.","SintaChat can provide the place where a conversation begins. Each user remains responsible for deciding what information they are comfortable sharing."]}
];

export default function About(){
 return <><SiteHeader/><main className="editorial-page about-page">
    <header className="editorial-hero"><p className="eyebrow">ABOUT SINTACHAT</p><h1>Connect. Talk. <em>Discover someone new.</em></h1><p className="editorial-lead">An anonymous online chat platform created for students aged 18 and above across the Philippines.</p><span className="editorial-orbit" aria-hidden="true"/></header>
  <div className="editorial-intro"><p>SintaChat is designed to make meeting and talking with new people simple, spontaneous, and accessible. Instead of building conversations around public profiles, follower counts, popularity, or carefully curated online identities, SintaChat places the conversation itself at the center of the experience.</p><p>Whether you are from Luzon, Visayas, or Mindanao, you can meet people from different cities, provinces, communities, schools, professions, and walks of life throughout the country.</p></div>
  <div className="editorial-sections">{SECTIONS.map(section=><section className="editorial-section" key={section.title}><div><h2>{section.title}</h2>{section.paragraphs.map(paragraph=><p key={paragraph}>{paragraph}</p>)}</div></section>)}</div>
  <section className="editorial-close"><p className="eyebrow">THIS IS SINTACHAT</p><h2>Meet someone new.<br/>Start a conversation.</h2><p>Developed by PUP Computer Engineering students.<br/>Built for students across the Philippines.<br/>Powered by conversation.</p></section>
 </main><SiteFooter/></>
}
