// National university suggestions for the SintaChat campus combobox.
// The field also accepts free text so a CHED-recognized institution/campus
// that is not yet in this suggestion list can still be used immediately.

export const PINNED_CAMPUSES = [
  "Other school / Rather not say",
  "Polytechnic University of the Philippines",
  "University of the Philippines",
];

export const STATE_UNIVERSITIES = [
  "University of the Philippines Baguio",
  "University of the Philippines Cebu",
  "University of the Philippines Diliman",
  "University of the Philippines Los Baños",
  "University of the Philippines Manila",
  "University of the Philippines Mindanao",
  "University of the Philippines Open University",
  "University of the Philippines Visayas",
  "Mindanao State University - Iligan Institute of Technology",
  "Aklan State University",
  "Bataan Peninsula State University",
  "Batangas State University",
  "Benguet State University",
  "Bicol University",
  "Bohol Island State University",
  "Bukidnon State University",
  "Bulacan Agricultural State University",
  "Bulacan State University",
  "Cagayan State University",
  "Capiz State University",
  "Caraga State University",
  "Carlos Hilado Memorial State University",
  "Catanduanes State University",
  "Cavite State University",
  "Cebu Normal University",
  "Cebu Technological University",
  "Central Bicol State University of Agriculture",
  "Central Luzon State University",
  "Central Mindanao University",
  "Cotabato State University",
  "Davao del Norte State University",
  "Davao Oriental State University",
  "Don Honorio Ventura State University",
  "Don Mariano Marcos Memorial State University",
  "Eastern Samar State University",
  "Eastern Visayas State University",
  "Ifugao State University",
  "Isabela State University",
  "Jose Rizal Memorial State University",
  "Kalinga State University",
  "Laguna State Polytechnic University",
  "Leyte Normal University",
  "Mariano Marcos State University",
  "Marinduque State University",
  "Mindanao State University",
  "Mountain Province State University",
  "Negros Oriental State University",
  "North Eastern Mindanao State University",
  "Northern Iloilo State University",
  "Nueva Ecija University of Science and Technology",
  "Nueva Vizcaya State University",
  "Palawan State University",
  "Pampanga State Agricultural University",
  "Partido State University",
  "Philippine Normal University",
  "Polytechnic State University of Bicol",
  "Quirino State University",
  "Romblon State University",
  "Samar State University",
  "Sorsogon State University",
  "Southern Leyte State University",
  "Southern Luzon State University",
  "Sultan Kudarat State University",
  "Surigao del Norte State University",
  "Tarlac Agricultural University",
  "Tarlac State University",
  "Technological University of the Philippines",
  "University of Antique",
  "University of Eastern Philippines",
  "University of Northern Philippines",
  "University of Rizal System",
  "University of Science and Technology of Southern Philippines",
  "University of Southeastern Philippines",
  "University of Southern Mindanao",
  "Visayas State University",
  "West Visayas State University",
  "Western Mindanao State University",
  "Western Philippines University",
  "Zamboanga Peninsula Polytechnic State University",
];

export const OTHER_PHILIPPINE_UNIVERSITIES = [
  "Adamson University",
  "Adventist University of the Philippines",
  "Ago Medical and Educational Center - Bicol Christian College of Medicine",
  "Aldersgate College",
  "AMA University",
  "Angeles University Foundation",
  "Arellano University",
  "Asia Pacific College",
  "Asian Institute of Management",
  "Asian Institute of Maritime Studies",
  "Assumption College San Lorenzo",
  "Ateneo de Davao University",
  "Ateneo de Manila University",
  "Ateneo de Naga University",
  "Ateneo de Zamboanga University",
  "Baliuag University",
  "Bataan Heroes College",
  "Batangas Eastern Colleges",
  "Bicol College",
  "Brokenshire College",
  "Cagayan de Oro College - PHINMA",
  "Capitol University",
  "Central Philippine University",
  "Centro Escolar University",
  "Chiang Kai Shek College",
  "Colegio de Dagupan",
  "Colegio de San Juan de Letran",
  "Colegio de San Juan de Letran Calamba",
  "Colegio de San Juan de Letran Bataan",
  "College of the Holy Spirit Manila",
  "Concordia College",
  "Davao Doctors College",
  "Davao Medical School Foundation",
  "De La Salle - College of Saint Benilde",
  "De La Salle Araneta University",
  "De La Salle Medical and Health Sciences Institute",
  "De La Salle University",
  "De La Salle University - Dasmariñas",
  "De La Salle Lipa",
  "De La Salle University - Laguna Campus",
  "Divine Word College of Calapan",
  "Divine Word College of Legazpi",
  "Divine Word College of Laoag",
  "Divine Word College of San Jose",
  "Divine Word College of Vigan",
  "Emilio Aguinaldo College",
  "Enderun Colleges",
  "Far Eastern University",
  "Far Eastern University - Alabang",
  "Far Eastern University - Cavite",
  "Far Eastern University - Diliman",
  "Far Eastern University - Dr. Nicanor Reyes Medical Foundation",
  "FEATI University",
  "Filamer Christian University",
  "First Asia Institute of Technology and Humanities",
  "Holy Angel University",
  "Holy Name University",
  "Holy Trinity University",
  "iACADEMY",
  "Immaculate Conception College of Balayan",
  "Jose Maria College Foundation",
  "José Rizal University",
  "La Consolacion College Bacolod",
  "La Consolacion College Manila",
  "La Consolacion University Philippines",
  "Liceo de Cagayan University",
  "Liceo de San Pedro",
  "Lyceum of the Philippines University",
  "Lyceum of the Philippines University - Batangas",
  "Lyceum of the Philippines University - Cavite",
  "Lyceum of the Philippines University - Laguna",
  "Manila Central University",
  "Manuel L. Quezon University",
  "Mapúa Malayan Colleges Laguna",
  "Mapúa Malayan Colleges Mindanao",
  "Mapúa University",
  "Maryknoll College of Panabo",
  "Miriam College",
  "National University",
  "National University - Baliwag",
  "National University - Clark",
  "National University - Dasmariñas",
  "National University - Fairview",
  "National University - Laguna",
  "National University - Lipa",
  "National University - Mall of Asia",
  "New Era University",
  "Notre Dame of Dadiangas University",
  "Notre Dame of Marbel University",
  "Notre Dame University",
  "Our Lady of Fatima University",
  "Our Lady of Fatima University - Antipolo",
  "Our Lady of Fatima University - Cabanatuan",
  "Our Lady of Fatima University - Laguna",
  "Our Lady of Fatima University - Pampanga",
  "Our Lady of Fatima University - Quezon City",
  "Our Lady of Fatima University - Valenzuela",
  "Pamantasan ng Lungsod ng Maynila",
  "Pamantasan ng Lungsod ng Muntinlupa",
  "Pamantasan ng Lungsod ng Pasig",
  "Pamantasan ng Lungsod ng Valenzuela",
  "Perpetual Help College of Manila",
  "Philippine Christian University",
  "Philippine Women's University",
  "PHINMA University of Iloilo",
  "PHINMA University of Pangasinan",
  "Rizal Technological University",
  "Saint Louis University",
  "Saint Mary's University",
  "San Beda College Alabang",
  "San Beda University",
  "San Pedro College",
  "Silliman University",
  "South Philippine Adventist College",
  "Southville International School and Colleges",
  "Southwestern University PHINMA",
  "St. Paul University Dumaguete",
  "St. Paul University Iloilo",
  "St. Paul University Manila",
  "St. Paul University Philippines",
  "St. Paul University Quezon City",
  "St. Scholastica's College Manila",
  "St. Dominic College of Asia",
  "STI College",
  "The Manila Times College",
  "Trinity University of Asia",
  "University of Asia and the Pacific",
  "University of Baguio",
  "University of Batangas",
  "University of Cebu",
  "University of Cebu - Banilad",
  "University of Cebu - Lapu-Lapu and Mandaue",
  "University of Cebu - METC",
  "University of Eastern Pangasinan",
  "University of La Salette",
  "University of Luzon",
  "University of Makati",
  "University of Manila",
  "University of Mindanao",
  "University of Negros Occidental - Recoletos",
  "University of Nueva Caceres",
  "University of Pangasinan",
  "University of Perpetual Help System DALTA",
  "University of Perpetual Help System DALTA - Calamba",
  "University of Perpetual Help System DALTA - Molino",
  "University of Perpetual Help System JONELTA",
  "University of Saint Anthony",
  "University of San Agustin",
  "University of San Carlos",
  "University of San Jose - Recoletos",
  "University of Santo Tomas",
  "University of Santo Tomas - Angelicum College",
  "University of Santo Tomas - Legazpi",
  "University of St. La Salle",
  "University of the Assumption",
  "University of the Cordilleras",
  "University of the East",
  "University of the East - Caloocan",
  "University of the East Ramon Magsaysay Memorial Medical Center",
  "University of the Immaculate Conception",
  "University of the Visayas",
  "Virgen Milagrosa University Foundation",
  "Wesleyan University Philippines",
  "Xavier University - Ateneo de Cagayan",
];

export const PHILIPPINE_UNIVERSITY_SUGGESTIONS = [
  ...PINNED_CAMPUSES,
  ...STATE_UNIVERSITIES.filter(name => !PINNED_CAMPUSES.includes(name)),
  ...OTHER_PHILIPPINE_UNIVERSITIES
].filter((name,index,array)=>array.indexOf(name)===index);
